spring:
  application:
    name: turbo-restaurant
  datasource:
    url: jdbc:postgresql://localhost:5432/turboresto
    username: andersonkouadio
    password: Leloup01@
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formatsql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# jwt token expiration time in hours
jwt:
  time-exp: 1

password:
  # nombre de tentative de connexion
  max-tentative: 3
  # delais d'expiration du mot de passe en jour
  expired-delay: 30
  # longueur du mot de passe
  length: 8

code-opt:
  # longueur du code opt
  length: 4
  # delai d'expiration du code en minute
  delay: 5

doc:
  root: /Users/andersonkouadio/Documents/Projets/TURBO DELIVERY/storage

front:
  base_url: http://localhost:3000

picture:
  max: 5
